Salvemos/Salvemos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.Users.urls')),
    path('', include('applications.Home.urls')),
    path('', include('applications.Posts.urls')),
    #
    path(r'ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Salvemos/applications/Posts/urls.py
"""Urls de la aplicación Posts"""
from django.urls import path
from . import views

app_name = "Posts_app"

urlpatterns = [
    path(
        'Posts/',
        views.PostsListView.as_view(),
        name='Posts-lista',
    ),
    path(
        'Post/<slug>/',
        views.PostsDetailView.as_view(),
        name='Post-detail',
    ),
    path(
        'NewPost/',
        views.NewPost.as_view(),
        name='NewPost',
    ),
]

Salvemos/applications/Users/urls.py
"""URls de la aplicación Users"""
from django.urls import path

from . import views

app_name = "Users_app"

urlpatterns = [
    path(
        'register/',
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'verification/<pk>/',
        views.CodVerificationView.as_view(),
        name='user-verification',
    ),
    path(
        'login/',
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/',
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'update/',
        views.UpdatePasswordView.as_view(),
        name='user-update',
    ),
    path(
        'profile/',
        views.UserPageListView.as_view(),
        name='user-profile',
    ),
    path(
        'addfavorito/<pk>/',
        views.addfavoritosView.as_view(),
        name='addfavorito',
    ),
    path(
        'deletefavorito/<pk>/',
        views.FavoritosDeleteView.as_view(),
        name='deletefavorito',
    ),
]

Salvemos/applications/Users/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import (
    AbstractBaseUser,
    PermissionsMixin,
)
from model_utils.models import TimeStampedModel
#
from .managers import UserManager, FavoritesManager
from applications.Posts.models import Posts
# Create your models here.


class User(AbstractBaseUser, PermissionsMixin):
    """Modelo para la creación de un usuario"""
    GENDER_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Femenino'),
        ('O', 'Otros'),
    )

    email = models.EmailField(unique=True)
    name = models.CharField('Nombres', max_length=30)
    last_name = models.CharField('Apellidos', max_length=40, blank=True)
    is_foundation = models.BooleanField(default=False)

    genero = models.CharField(
        max_length=1,
        choices=GENDER_CHOICES,
        blank=True
    )
    date_birth = models.DateField(
        'Fecha de nacimiento',
        blank=True,
        null=True
    )
    #
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    codregistro = models.CharField(max_length=6, default='000000')

    USERNAME_FIELD = 'email'

    REQUIRED_FIELDS = ['name']

    objects = UserManager()

    def get_short_name(self):
        return self.name

    def get_full_name(self):
        return self.name + ' ' + self.last_name


class Favorites(TimeStampedModel):
    """Modelo para los favoritos de un usuario"""
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='user_favorites',
        on_delete=models.CASCADE,
    )
    post = models.ForeignKey(
        Posts,
        related_name='posts_favorites',
        on_delete=models.CASCADE,
    )
    objects = FavoritesManager()

    class Meta:
        unique_together = ('user', 'post')
        verbose_name = 'Post Favorito'
        verbose_name_plural = 'Posts Favoritos'

    def __str__(self):
        return self.post.title

Salvemos/applications/Users/forms.py
from django import forms
from django.contrib.auth import authenticate
#
from .models import User


class UserRegisterForm(forms.ModelForm):
    """Formulario para registrar un usuario"""
    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Ingresa una contraseña',
                'class': 'input__login',
            }
        )
    )
    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Escribe nuevamente la contraseña',
                'class': 'input__login',
            }
        )
    )

    class Meta:
        """Meta definition for Userform."""

        model = User
        fields = (
            'email',
            'name',
            'last_name',
            'is_foundation',
            'genero',
            'date_birth',
        )
        widgets = {
            'email': forms.EmailInput(
                attrs={
                    'placeholder': 'Correo Electronico',
                    'class': 'input__login',
                }
            ),
            'name': forms.TextInput(
                attrs={
                    'placeholder': 'Ingresa tu nombre',
                    'class': 'input__login',
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'placeholder': 'Ingresa tus apellidos',
                    'class': 'input__login',
                }
            ),
            'genero': forms.Select(
                attrs={
                    'placeholder': 'Genero',
                    'class': 'input__login',
                }
            ),
            'date_birth': forms.DateInput(
                attrs={
                    'type': 'date',
                }
            ),
            'is_foundation': forms.CheckboxInput(
            ),
        }
    # Valida si las contraseñas son iguales

    def clean_password2(self):
        if self.cleaned_data['password1'] != self.cleaned_data['password2']:
            self.add_error('password2', 'Las contraseñas no son iguales')


class LoginForm(forms.Form):
    """Formulario para iniciar sesión"""
    email = forms.CharField(
        # label='E-mail',
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Ingresa tu correo electrónico',
                'class': 'input__login',
            }
        )
    )
    password = forms.CharField(
        # label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Ingresa tu contraseña',
                'class': 'input__login',
            }
        )
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']

        if not authenticate(email=email, password=password):
            raise forms.ValidationError(
                'Los datos de usuario no son correctos')

        return self.cleaned_data


class UpdatePasswordForm(forms.Form):
    """Formulario para actualizar la contraseña"""
    password1 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña Actual',
                'class': 'input__login',
            }
        )
    )
    password2 = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Contraseña Nueva',
                'class': 'input__login',
            }
        )
    )


class VerificationForm(forms.Form):
    """Formulario para la validar el código de verificación"""
    codregistro = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Ingresa tu código de verificación',
                'class': 'input__login',
            }
        )
    )

    # se sobreescribre __init__ para recuperar los
    # kwargs adicionales enviados desde las views
    def __init__(self, pk, *args, **kwargs):
        self.id_user = pk
        super(VerificationForm, self).__init__(*args, **kwargs)

    def clean_codregistro(self):
        """Esta función valida que el códig de registro le pertenezca al usuario
        llamando al manager cod_validation que devuelve True si es valido"""
        # se recupera el código para realizar la validación
        codigo = self.cleaned_data['codregistro']

        if len(codigo) == 6:
            # verificamos si el codigo y el id de usuario son validos
            activo = User.objects.cod_validation(
                self.id_user,
                codigo
            )
            if not activo:
                raise forms.ValidationError('El código es incorrecto')
        else:
            raise forms.ValidationError('El código es incorrecto')

Salvemos/applications/Users/views.py
""""Vistas de la aplicación Users"""
# Imports Django
from django.core.mail import send_mail
from django.urls import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from .functions import *

from django.views.generic import (
    View,
    ListView,
    DeleteView
)

from django.views.generic.edit import (
    FormView
)
# Imports propios
from .forms import (
    UserRegisterForm,
    LoginForm,
    UpdatePasswordForm,
    VerificationForm,
)
#
from .models import User, Favorites
from applications.Posts.models import Posts
#


class UserRegisterView(FormView):
    """Vista para registrar un usuario"""
    template_name = 'Users/signup.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('Users_app:user-login')

    def form_valid(self, form):
        # Se crea el código de verificación
        codigo = code_generator()

        usuario = User.objects.create_user(
            form.cleaned_data['email'],
            form.cleaned_data['password1'],
            name=form.cleaned_data['name'],
            last_name=form.cleaned_data['last_name'],
            is_foundation=form.cleaned_data['is_foundation'],
            genero=form.cleaned_data['genero'],
            date_birth=form.cleaned_data['date_birth'],
            codregistro=codigo,
        )
        # Enviar email al usuario
        asunto = 'Email de confirmación'
        message = 'Tu código de registro para salvemos ' + codigo
        from_email = 'lermasama@gmail.com'
        send_mail(asunto, message, from_email, [form.cleaned_data['email'], ])
        # Una vez confirmado redirigir a pantalla de confirmación

        return HttpResponseRedirect(
            reverse(
                'Users_app:user-verification',
                kwargs={'pk': usuario.id}
            )
        )


class LoginUser(FormView):
    """"Vista para iniciar sesión"""
    template_name = 'Users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('Posts_app:Posts-lista')

    def form_valid(self, form):
        user = authenticate(
            email=form.cleaned_data['email'],
            password=form.cleaned_data['password']
        )
        login(self.request, user)
        return super(LoginUser, self).form_valid(form)


class LogoutView(View):
    """Vista para cerrar sesión"""

    def get(self, request, *args, **kargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'Users_app:user-login'
            )
        )


class UpdatePasswordView(LoginRequiredMixin, FormView):
    """Vista para actualizar la contraseña"""
    template_name = 'users/update_password.html'
    form_class = UpdatePasswordForm
    success_url = reverse_lazy('Users_app:user-login')
    login_url = reverse_lazy('Users_app:user-login')

    def form_valid(self, form):
        usuario = self.request.user
        user = authenticate(
            email=usuario.email,
            password=form.cleaned_data['password1']
        )

        if user:
            new_password = form.cleaned_data['password2']
            usuario.set_password(new_password)
            usuario.save()

        logout(self.request)
        return super(UpdatePasswordView, self).form_valid(form)


class UserPageListView(LoginRequiredMixin, ListView):
    """Vista mostrar la cuenta de un usuario"""
    template_name = "Users/profile.html"
    context_object_name = 'profileuser'
    login_url = reverse_lazy('Users_app:user-login')

    def get_queryset(self):
        return Favorites.objects.posts_user(self.request.user)


class addfavoritosView(View):
    """Vista para añadir un favorito"""

    def post(self, request, *args, **kwargs):
        # se recupera el usuario
        usuario = self.request.user
        # se recupera la entrada o pk
        post = Posts.objects.get(id=self.kwargs['pk'])
        # se registra el objeto favorito
        Favorites.objects.create(
            user=usuario,
            post=post,
        )

        return HttpResponseRedirect(reverse('Users_app:user-profile'))


class FavoritosDeleteView(DeleteView):
    """Vista para eliminar un favorito"""
    model = Favorites
    success_url = reverse_lazy('Users_app:user-profile')


class CodVerificationView(FormView):
    """Vista para ingresar el código de verificación"""
    template_name = 'Users/verification.html'
    form_class = VerificationForm
    success_url = reverse_lazy('Users_app:user-login')

    # Se sobreescribe get_form_kwargs para que envíe nuevos kwargs al
    # formulario y poder recuperar el id de la url
    def get_form_kwargs(self):
        kwargs = super(CodVerificationView, self).get_form_kwargs()
        kwargs.update({
            'pk': self.kwargs['pk']
        })
        return kwargs

    def form_valid(self, form):
        User.objects.filter(
            id=self.kwargs['pk']
        ).update(
            is_active=True
        )
        return super(CodVerificationView, self).form_valid(form)

Salvemos/templates/Users/base_users.html
{% extends "base.html" %}

{% load  static %}

{% block css %}

{% endblock css %}

{% block content %}

{% endblock content %}

{% block js %}

{% endblock js %}

Salvemos/templates/Users/login.html
{% extends "Users/base_users.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/style-login.css' %}">
{% endblock css %}

{% block title %}
Iniciar Sesión
{% endblock title %}

{% block content %}
{% include 'includes/header_login_signup.html' %}

<section class="login">
    <figure class="login__picture">
        <img src="{% static 'img/imglogin.svg' %}" alt="Imagen del login" class="login__img">
    </figure>

    <form class="login__form" method="post" enctype="multipart/form-data">{% csrf_token %}
        <h2 class="login__title title">Ingresa a tu cuenta</h2>
        {{form.email}}
        {{form.password}}
        <div class="login__btn">
            <button type="submit" class="login__cta">Inicia sesión</button>
            <p class="login__text">No tienes una cuenta? </p>
            <a href="{% url 'Users_app:user-register' %}" class="login__signup">Registrate</a>
        </div>


    </form>
</section>
{% endblock content %}

Salvemos/templates/Users/profile.html
{% extends "Posts/base_posts.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/style-profile.css' %}">
<script src="https://kit.fontawesome.com/b814c54e34.js" crossorigin="anonymous"></script>
{% endblock css %}

{% block title %}
Nuevo Post
{% endblock title %}

{% block content %}
{% include 'includes/header_posts.html' %}

<section class="container">
    <div class="perfil">
        <div class="card">
            <h2 class="card_title">{{user.name}} {{user.last_name}}</h2>
            <h3 class="card_text">{{user.email}}</h3>
            <h3 class="card_text">{{user.date_birth}}</h3>
            <a href="{% url 'Users_app:user-update' %}" class="cta">Cambiar contraseña</a>
        </div>
    </div>
    <div class="titlefavorite">
        <h2 class="card_title">Mis favoritos</h2>
        <div class="containerfavoritos">

            {% for favorito in profileuser %}
            <div class="feed__item">
                <div class="feed__figure">
                    <img src="{{favorito.post.image.url}}" class="feed__img">
                </div>
                <div class="feed__texts">
                    <h2 class="feed__title">{{favorito.post.title}}</h2>
                    <p class="feed__paragraph">{{favorito.post.resume}}</p>
                    <form action="{% url 'Users_app:deletefavorito' favorito.id %}" method="post">{% csrf_token %}
                        <a href="{% url 'Posts_app:Post-detail' favorito.post.slug %}" class="cta cta_card">Ver</a>
                        <button type="submit" class="cta cta_card cta_eliminar">Eliminar</button>
                    </form>
                </div>
            </div>
            {%empty%}
            <h3>No tienes favoritos</h3>
            {% endfor %}

        </div>
    </div>


</section>


{% include 'includes/footer.html' %}
{% endblock content %}

Salvemos/templates/Users/signup.html
{% extends "Users/base_users.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/style-signup.css' %}">
{% endblock css %}

{% block title %}
Registrate
{% endblock title %}

{% block content %}
{% include 'includes/header_login_signup.html' %}

<section class="login">
    <figure class="login__picture">
        <img src="{% static 'img/imglogin.svg' %}" alt="Imagen del login" class="login__img">
    </figure>

    <form class="login__form" method="post" enctype="multipart/form-data">{% csrf_token %}
        <h2 class="login__title title">Registrate</h2>
        {{form.name}}
        {{form.last_name}}
        {{form.email}}
        <p>Eres una fundación? {{form.is_foundation}}</p>
        {{ form.genero }}
        <p>Ingresa tu fecha de nacimiento</p>
        {{ form.date_birth }}
        {{ form.password1 }}
        {{ form.password2 }}

        <div class="login__btn">
            <button type="submit" class="login__cta">Registrarse</button>
            <p class="login__text">Ya tienes una cuenta? </p>
            <a href="{% url 'Users_app:user-login' %}" class="login__singup">Inicia sesión</a>
        </div>


    </form>
</section>

{% endblock content %}

Salvemos/templates/Users/update_password.html
{% extends "Users/base_users.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/style-update_password.css' %}">
{% endblock css %}

{% block title %}
Actualizar contraseña
{% endblock title %}

{% block content %}
{% include 'includes/header_posts.html' %}

<section class="login">
    <figure class="login__picture">
        <img src="{% static 'img/imgforgotpassword.svg' %}" alt="Imagen del login" class="login__img">
    </figure>

    <form class="login__form" method="post" enctype="multipart/form-data">{% csrf_token %}
        <h2 class="login__title title">Actualiza tu contraseña</h2>
        {{form.password1}}
        {{form.password2}}
        <div class="login__btn">
            <button type="submit" class="login__cta">Actualizar</button>
        </div>


    </form>
</section>
{% endblock content %}

Salvemos/templates/Users/verification.html
{% extends "Users/base_users.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/style-signup.css' %}">
{% endblock css %}

{% block title %}
Registrate
{% endblock title %}

{% block content %}
{% include 'includes/header_login_signup.html' %}

<section class="login">
    <figure class="login__picture">
        <img src="{% static 'img/imgconfirmationcode.svg' %}" alt="Imagen del login" class="login__img">
    </figure>

    <form class="login__form" method="post">{% csrf_token %}
        <h2 class="login__title title">Ingresa tu código de registro</h2>
        {{form.codregistro}}
        <div class="login__btn">
            <button type="submit" class="login__cta">Activa tu cuenta</button>
        </div>


    </form>
</section>

{% endblock content %}