Salvemos/Salvemos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.Users.urls')),
    path('', include('applications.Home.urls')),
    path('', include('applications.Posts.urls')),
    #
    path(r'ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Salvemos/applications/Home/urls.py
"""Urls de la aplicación Home"""
from django.urls import path

from . import views

app_name = "Home_app"

urlpatterns = [
    path(
        '',
        views.HomePageView.as_view(),
        name='index',
    ),
    path(
        'contactanos/',
        views.ContactView.as_view(),
        name='contactanos',
    ),
]

Salvemos/applications/Posts/urls.py
"""Urls de la aplicación Posts"""
from django.urls import path
from . import views

app_name = "Posts_app"

urlpatterns = [
    path(
        'Posts/',
        views.PostsListView.as_view(),
        name='Posts-lista',
    ),
    path(
        'Post/<slug>/',
        views.PostsDetailView.as_view(),
        name='Post-detail',
    ),
    path(
        'NewPost/',
        views.NewPost.as_view(),
        name='NewPost',
    ),
]

Salvemos/applications/Users/urls.py
"""URls de la aplicación Users"""
from django.urls import path

from . import views

app_name = "Users_app"

urlpatterns = [
    path(
        'register/',
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'verification/<pk>/',
        views.CodVerificationView.as_view(),
        name='user-verification',
    ),
    path(
        'login/',
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/',
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'update/',
        views.UpdatePasswordView.as_view(),
        name='user-update',
    ),
    path(
        'profile/',
        views.UserPageListView.as_view(),
        name='user-profile',
    ),
    path(
        'addfavorito/<pk>/',
        views.addfavoritosView.as_view(),
        name='addfavorito',
    ),
    path(
        'deletefavorito/<pk>/',
        views.FavoritosDeleteView.as_view(),
        name='deletefavorito',
    ),
]

Salvemos/applications/Home/models.py
from django.db import models
from model_utils.models import TimeStampedModel

# Create your models here.


class Contact(TimeStampedModel):
    """Modelo para formulario de contacto"""
    full_name = models.CharField('Nombres', max_length=60)
    email = models.EmailField()
    message = models.TextField()

    class Meta:
        verbose_name = 'Contacto'
        verbose_name_plural = 'Mensaje'

    def __str__(self):
        return self.full_name

Salvemos/applications/Home/forms.py
from django import forms
#
from .models import Contact


class ContactForm(forms.ModelForm):
    """Formulario para la vista de contacto"""
    class Meta:
        model = Contact
        fields = (
            'full_name',
            'email',
            'message',
        )
        widgets = {
            'full_name': forms.TextInput(
                attrs={
                    'placeholder': 'Ingresa tu nombre:',
                    'class': 'input__contact',
                }
            ),
            'email': forms.EmailInput(
                attrs={
                    'placeholder': 'Ingresa tu correo:',
                    'class': 'input__contact',
                }
            ),
            'message': forms.Textarea(
                attrs={
                    'placeholder': 'Ingresa tu mensaje:',
                    'class': 'input__contact contact__input--area',
                }
            ),
        }

Salvemos/applications/Home/views.py
"""Vistas de la aplicación Home"""
from django.urls import reverse_lazy
from django.views.generic import (
    FormView,
    TemplateView,
)
from applications.Posts.models import Posts
from .forms import *
from .models import Contact


class HomePageView(TemplateView):
    """Vista para la página de inicio o index"""
    template_name = "Home/index.html"

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        # Contexto para enviar a la seccion de nuestro trabajo los
        # ultimos post de la sección adoptar
        context["post_adoptar"] = Posts.objects.Post_en_portada_adopcion()
        # Contexto para enviar a la seccion de nuestro trabajo los
        # ultimos post de la sección apadrinar
        context["post_apadrinar"] = Posts.objects.Post_en_portada_apadrinar()
        # Contexto para enviar a la seccion de nuestro trabajo los
        # ultimos post de la sección donar
        context["post_donar"] = Posts.objects.Post_en_portada_donar()
        return context


class ContactView(FormView):
    """Vista de la página de contacto"""
    template_name = 'Home/contacto.html'
    form_class = ContactForm
    success_url = reverse_lazy('Home_app:index')

    def form_valid(self, form):
        # función que recoge los datos de la sección de contacto y los ingresa a la base de datos
        full_name = form.cleaned_data['full_name']
        email = form.cleaned_data['email']
        message = form.cleaned_data['message']
        Contact.objects.create(
            full_name=full_name,
            email=email,
            message=message,
        )
        return super(ContactView, self).form_valid(form)

Salvemos/templates/Home/contacto.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contáctanos</title>
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/style-contacto.css' %}">
</head>

<body>
    <section class="contact">
        <form class="contact__form" method="post" enctype="multipart/form-data">{% csrf_token %}
            <h2 class="contact__title">Contáctanos</h2>

            {{form.as_p}}
            <div class="button">
                <button type="submit" class="contact__cta">Enviar</button>

                {% if not user.is_anonymous %}
                <a href="{% url 'Posts_app:Posts-lista' %}">Inicio</a>
                {% else %}
                <a href="{% url 'Home_app:index' %}">Inicio</a>
                {% endif %}


            </div>

        </form>

    </section>
</body>

</html>

Salvemos/templates/Home/index.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Salvemos</title>
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/style-index.css' %}">
    <script src="https://kit.fontawesome.com/b814c54e34.js" crossorigin="anonymous"></script>
</head>

<body class="hidden">
    <div class="centrado" id="onload">
        <div class="lds-ellipsis">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <header>
        <nav id="nav" class="nav1">
            <div class="contenedor-nav">
                <div class="logo">
                    <img src="{% static 'icons/004-pawprint.png' %}" alt="">
                </div>
                <div class="enlaces" id="enlaces">
                    <a href="#" id="enlace-inicio" class="btn-header">Inicio</a>
                    <a href="#" id="enlace-equipo" class="btn-header">Equipo</a>
                    <a href="#" id="enlace-servicio" class="btn-header">Servicio</a>
                    <a href="#" id="enlace-trabajo" class="btn-header">Trabajo</a>
                    <a href="#" id="enlace-contacto" class="btn-header">Contacto</a>
                    <a href="{% url 'Users_app:user-login' %}" class="btn-header">Ingresar</a>
                    <a href="{% url 'Users_app:user-register' %}" class="btn-header">Registrarme</a>
                </div>
                <div class="icono" id="open">
                    <span>&#9776;</span>
                </div>
            </div>
        </nav>
        <div class="textos">
            <h1>Salvemos</h1>
            <h2>Ayudando angelitos que no pueden hablar</h2>
        </div>
    </header>
    <main>
        <section class="team contenedor" id="equipo">
            <h3>Nuestro equipo</h3>
            <p class="after">Conoce a nuestro gran equipo</p>
            <div class="card">
                <div class="content-card">
                    <div class="people">
                        <img src="{% static 'img/equipotrabajo.jpg' %}" alt="imgequipotrabajo" width=100%>
                    </div>
                    <div class="texto-team">
                        <h4>K</h4>
                        <p>Me imagino que aqui va la descripcion</p>
                    </div>
                </div>
                <div class="content-card">
                    <div class="people">
                        <img src="{% static 'img/mascota2.jpg' %}" alt="mascota2" width=100%>
                    </div>
                    <div class="texto-team">
                        <h4>M</h4>
                        <p>Me imagino que aqui va la descripcion</p>
                    </div>
                </div>
                <div class="content-card">
                    <div class="people">
                        <img src="{% static 'img/mascota3.jpg' %}" alt="mascota3" width=100%>
                    </div>
                    <div class="texto-team">
                        <h4>N</h4>
                        <p>Me imagino que aqui va la descripcion</p>
                    </div>
                </div>
            </div>
        </section>
        <section class="about" id="servicio">
            <div class="contenedor">
                <h3>Nuestros servicios</h3>
                <p class="after">Pequeños gestos <br> Grandes acciones</p>
                <div class="servicios">
                    <div class="caja-servicios">
                        <img src="{% static 'icons/001-animal.png' %}" alt="">
                        <h4>Dona</h4>
                        <p>Puedes realizar donaciones <br> a la fundación que desees</p>
                    </div>
                    <div class="caja-servicios">
                        <img src="{% static 'icons/002-pet-house.png' %}" alt="">
                        <h4>Apadrina</h4>
                        <p>Si no tienes espacio en tu <br> casa no te preocupes <br> apadrina una mascota y <br>
                            nosotros nos encargarmos del resto</p>
                    </div>
                    <div class="caja-servicios">
                        <img src="{% static 'icons/003-happy.png' %}" alt="">
                        <h4>Adopta</h4>
                        <p>Lleva a ese peludito que <br> tanto quieres a tu casa <br> para que la llene de amor</p>
                    </div>
                </div>
            </div>
        </section>
        <section class="work contenedor" id="trabajo">
            <h3>Nuestro trabajo</h3>
            <p class="after">Hacemos grandes cosas</p>
            <div class="botones-work">
                <ul>
                    <li class="filter active" data-nombre="todos">Todos</li>
                    <li class="filter" data-nombre="adoptar">Adopcion</li>
                    <li class="filter" data-nombre="apadrinar">Apadrinar</li>
                    <li class="filter" data-nombre="donar">Donar</li>
                </ul>
            </div>
            <div class="galeria-work">

                {% for post in post_adoptar %}

                <div class="cont-work adoptar">
                    <a class="textos-work-link" href="{% url 'Posts_app:Post-detail' post.id %}">
                        <div class="img-work">
                            <img src="{{ post.image.url }}" alt="" width=30%>
                        </div>
                        <div class="textos-work">
                            <h4 class="title">{{post.title}}</h4>
                        </div>
                    </a>
                </div>

                {% endfor %}

                {% for post in post_apadrinar %}
                <div class="cont-work adoptar">
                    <a class="textos-work-link" href="{% url 'Posts_app:Post-detail' post.id %}">
                        <div class="img-work">
                            <img src="{{ post.image.url }}" alt="" width=30%>
                        </div>
                        <div class="textos-work">
                            <h4 class="title">{{post.title}}</h4>
                        </div>
                    </a>
                </div>
                {% endfor %}


                {% for post in post_donar %}
                <div class="cont-work adoptar">
                    <a class="textos-work-link" href="{% url 'Posts_app:Post-detail' post.id %}">
                        <div class="img-work">
                            <img src="{{ post.image.url }}" alt="" width=30%>
                        </div>
                        <div class="textos-work">
                            <h4 class="title">{{post.title}}</h4>
                        </div>
                    </a>
                </div>
                {% endfor %}

            </div>
        </section>
    </main>
    {% include 'includes/footer.html' %}

    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/filtro.js' %}"></script>

</body>

</html>