Salvemos/Salvemos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.Users.urls')),
    path('', include('applications.Home.urls')),
    path('', include('applications.Posts.urls')),
    #
    path(r'ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Salvemos/applications/Home/urls.py
"""Urls de la aplicación Home"""
from django.urls import path

from . import views

app_name = "Home_app"

urlpatterns = [
    path(
        '',
        views.HomePageView.as_view(),
        name='index',
    ),
    path(
        'contactanos/',
        views.ContactView.as_view(),
        name='contactanos',
    ),
]

Salvemos/applications/Posts/urls.py
"""Urls de la aplicación Posts"""
from django.urls import path
from . import views

app_name = "Posts_app"

urlpatterns = [
    path(
        'Posts/',
        views.PostsListView.as_view(),
        name='Posts-lista',
    ),
    path(
        'Post/<slug>/',
        views.PostsDetailView.as_view(),
        name='Post-detail',
    ),
    path(
        'NewPost/',
        views.NewPost.as_view(),
        name='NewPost',
    ),
]

Salvemos/applications/Users/urls.py
"""URls de la aplicación Users"""
from django.urls import path

from . import views

app_name = "Users_app"

urlpatterns = [
    path(
        'register/',
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'verification/<pk>/',
        views.CodVerificationView.as_view(),
        name='user-verification',
    ),
    path(
        'login/',
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/',
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'update/',
        views.UpdatePasswordView.as_view(),
        name='user-update',
    ),
    path(
        'profile/',
        views.UserPageListView.as_view(),
        name='user-profile',
    ),
    path(
        'addfavorito/<pk>/',
        views.addfavoritosView.as_view(),
        name='addfavorito',
    ),
    path(
        'deletefavorito/<pk>/',
        views.FavoritosDeleteView.as_view(),
        name='deletefavorito',
    ),
]

Salvemos/templates/includes/footer.html
{% load static %}
<footer id="contacto">
    <div class="footer contenedor">
        <div class="marca-logo">
            <br><br><br><br><br><br><br><br><br><br>
        </div>
        <div class="footer__icons">
            <a href="#" class="footer__icon fab fa-facebook-f"></a>
            <a href="#" class="footer__icon fab fa-twitter"></a>
            <a href="#" class="footer__icon fab fa-instagram"></a>
        </div>

        <div class="footer__nav">
            <p class="footer__text">Ó dejanos un <a href="{% url 'Home_app:contactanos' %}"
                    class="footer__link">mensaje</a></p>

        </div>

        <p class="footer__copy">Derechos reservados &copy; Salvemos</p>
    </div>
    </div>

</footer>

Salvemos/templates/includes/header_login_signup.html
{% load static %}
<header>
    <nav id="nav" class="nav1">
        <div class="contenedor-nav">
            <div class="logo">
                <img src="{% static 'icons/004-pawprint.png' %}" alt="">
            </div>
            <div class="enlaces" id="enlaces">
                <a href="{% url 'Home_app:index' %}" id="enlace-inicio" class="btn-header">Inicio</a>
                <a href="{% url 'Home_app:index' %}#equipo" id="enlace-equipo" class="btn-header">Equipo</a>
                <a href="{% url 'Home_app:index' %}#servicio" id="enlace-servicio" class="btn-header">Servicio</a>
                <a href="{% url 'Home_app:index' %}#trabajo" id="enlace-trabajo" class="btn-header">Trabajo</a>
                <a href="{% url 'Home_app:index' %}#contacto" id="enlace-contacto" class="btn-header">Contacto</a>
            </div>
            <!-- <div class="icono" id="open">
                <span>&#9776;</span>
            </div> -->
        </div>
    </nav>
</header>

Salvemos/templates/includes/header_posts.html
{% load static %}
<header>
    <nav id="nav" class="nav1">
        <div class="contenedor-nav">
            <div class="logo">
                <img src="{% static 'icons/004-pawprint.png' %}" alt="">
            </div>
            <div class="enlaces" id="enlaces">
                <a href="{% url 'Posts_app:Posts-lista' %}" id="enlace-inicio" class="btn-header">Inicio</a>
                <a href="{% url 'Posts_app:NewPost' %}" id="enlace-publicar" class="btn-header">Publicar</a>
                <a href="{% url 'Users_app:user-profile' %}" id="enlace-mi_cuenta" class="btn-header">Mi cuenta</a>
                <a href="{% url 'Users_app:user-logout' %}" id="enlace-salir" class="btn-header">Salir</a>
            </div>
            <!-- <div class="icono" id="open">
                <span>&#9776;</span>
            </div> -->
        </div>
    </nav>
</header>