Salvemos/Salvemos/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.Users.urls')),
    path('', include('applications.Home.urls')),
    path('', include('applications.Posts.urls')),
    #
    path(r'ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Salvemos/applications/Posts/urls.py
"""Urls de la aplicación Posts"""
from django.urls import path
from . import views

app_name = "Posts_app"

urlpatterns = [
    path(
        'Posts/',
        views.PostsListView.as_view(),
        name='Posts-lista',
    ),
    path(
        'Post/<slug>/',
        views.PostsDetailView.as_view(),
        name='Post-detail',
    ),
    path(
        'NewPost/',
        views.NewPost.as_view(),
        name='NewPost',
    ),
]

Salvemos/applications/Users/urls.py
"""URls de la aplicación Users"""
from django.urls import path

from . import views

app_name = "Users_app"

urlpatterns = [
    path(
        'register/',
        views.UserRegisterView.as_view(),
        name='user-register',
    ),
    path(
        'verification/<pk>/',
        views.CodVerificationView.as_view(),
        name='user-verification',
    ),
    path(
        'login/',
        views.LoginUser.as_view(),
        name='user-login',
    ),
    path(
        'logout/',
        views.LogoutView.as_view(),
        name='user-logout',
    ),
    path(
        'update/',
        views.UpdatePasswordView.as_view(),
        name='user-update',
    ),
    path(
        'profile/',
        views.UserPageListView.as_view(),
        name='user-profile',
    ),
    path(
        'addfavorito/<pk>/',
        views.addfavoritosView.as_view(),
        name='addfavorito',
    ),
    path(
        'deletefavorito/<pk>/',
        views.FavoritosDeleteView.as_view(),
        name='deletefavorito',
    ),
]

Salvemos/applications/Posts/models.py
"""Modelos de la aplicación entradas"""
from datetime import timedelta, datetime
from django.db import models
from django.conf import settings
from django.template.defaultfilters import slugify
from django.urls import reverse_lazy
from django.db.models.deletion import CASCADE
# App terceros
from model_utils.models import TimeStampedModel
from ckeditor_uploader.fields import RichTextUploadingField
# Managers
from .managers import PostsManager


class Category(TimeStampedModel):
    """Categorias de una entrada"""
    name = models.CharField('Nombre', max_length=30, unique=True)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return str(self.id) + '. ' + self.name


class Tag(TimeStampedModel):
    """Etiquetas de un articulo"""
    name = models.CharField('Nombre', max_length=30)

    class Meta:
        verbose_name = 'Etiqueta'
        verbose_name_plural = 'Tags'

    def __str__(self):
        return self.name


class Posts(TimeStampedModel):
    """Modelo para los Posts"""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
    )
    tag = models.ManyToManyField(Tag)
    title = models.CharField(
        'Titulo',
        max_length=200
    )
    resume = models.TextField('Resumen')
    content = RichTextUploadingField('Contenido')
    public = models.BooleanField(default=False)
    image = models.ImageField(
        'Imagen',
        upload_to='Posts'
    )
    slug = models.SlugField(editable=False, max_length=300)

    objects = PostsManager()

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = 'Posts'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy(
            'Posts_app:Posts-detail',
            kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        # Se reescribe la funcion save para modificar el slug y que quede como unico para usarlo en las urls
        # Calculamos el total de segundos de la hora actual
        now = datetime.now()
        total_time = timedelta(
            hours=now.hour,
            minutes=now.minute,
            seconds=now.second,
        )
        seconds = int(total_time.total_seconds())
        slug_unique = '%s %s' % (self.title, str(seconds))

        self.slug = slugify(slug_unique)
        super(Posts, self).save(*args, **kwargs)

Salvemos/applications/Posts/forms.py
from django import forms
from .models import Posts
from ckeditor.widgets import CKEditorWidget


class NewPostForm(forms.ModelForm):
    """Formulario para crear nuevas publicaciones"""
    content = forms.CharField(widget=CKEditorWidget())

    class Meta:
        model = Posts
        fields = (
            'category',
            'title',
            'resume',
            'image',
        )
        widgets = {
            'category': forms.Select(
                attrs={
                    'class': 'input__newpost',
                }
            ),
            'title': forms.TextInput(
                attrs={
                    'class': 'input__newpost',
                }
            ),
            'resume': forms.TextInput(
                attrs={
                    'class': 'input__newpost',
                }
            ),
            'public': forms.ImageField(
                label='Sube una imagen de la mascota',
            ),

        }

Salvemos/applications/Posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
)
from django.views.generic.edit import FormView
from .models import Posts, Category
from .forms import *

# Create your views here.


class PostsListView(LoginRequiredMixin, ListView):
    """Vista para mostrar los posts en el feed"""
    template_name = "Posts/feed.html"
    context_object_name = 'Posts'
    paginate_by = 8
    ordering = 'title'
    login_url = reverse_lazy('Users_app:user-login')

    def get_context_data(self, **kwargs):
        context = super(PostsListView, self).get_context_data(**kwargs)
        context["categorias"] = Category.objects.all()
        return context

    def get_queryset(self):
        kword = self.request.GET.get("kword", '')
        categoria = self.request.GET.get("categoria", '')

        # COnsulta de busqueda
        resultado = Posts.objects.buscar_Post(kword, categoria)
        return resultado


class PostsDetailView(LoginRequiredMixin, DetailView):
    """Vista para el detalle de una publicación"""
    model = Posts
    template_name = "Posts/post_detail.html"
    login_url = reverse_lazy('Users_app:user-login')


class NewPost(LoginRequiredMixin, FormView):
    """Vista para realizar una nueva publicación"""
    template_name = 'Posts/new_post.html'
    form_class = NewPostForm
    success_url = reverse_lazy('Posts_app:Posts-lista')
    login_url = reverse_lazy('Users_app:user-login')

    def form_valid(self, form):
        usuario = self.request.user
        Posts.objects.create(
            user=usuario,
            category=form.cleaned_data['category'],
            title=form.cleaned_data['title'],
            resume=form.cleaned_data['resume'],
            content=form.cleaned_data['content'],
            image=form.cleaned_data['image'],
            public=True,
        )
        return super(NewPost, self).form_valid(form)

Salvemos/templates/Posts/base_posts.html
{% extends "base.html" %}

{% load  static %}

{% block css %}

{% endblock css %}

{% block content %}

{% endblock content %}

{% block js %}

{% endblock js %}

Salvemos/templates/Posts/feed.html
{% extends "Posts/base_posts.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/style-feed.css' %}">
<script src="https://kit.fontawesome.com/b814c54e34.js" crossorigin="anonymous"></script>
{% endblock css %}

{% block title %}
Mascotas
{% endblock title %}

{% block content %}
{% include 'includes/header_posts.html' %}
<section class="feed container">
    <div class="buscador">
        <form method="get">{% csrf_token %}
            <div class="busc">
                <input type="text" name="kword" id="kword" class="barrabuscar" placeholder="Busca un post">
                <button type="submit" class="cta cta2">Buscar</button>
            </div>

            <div class="buscador">
                <h2>Filtra por categoria</h2>
                {% for categoria in categorias %}
                <a class="categoria" href="?categoria={{categoria.name}}">{{categoria.name}} | </a>
                {% endfor %}
        </form>
    </div>

    </div>

    <div class="feed__grid">
        {% for post in Posts %}
        <div class="feed__item">
            <div class="feed__figure">
                <img src="{{post.image.url}}" class="feed__img">
            </div>
            <div class="feed__texts">
                <h2 class="feed__title">{{post.title}}</h2>
                <h4 class="feed__paragraph resume">{{post.resume | truncatechars:40}}</h4>
                <p class="feed__paragraph content">{{post.content | truncatechars:100 | safe}}</p>
            </div>
            <a href="{% url 'Posts_app:Post-detail' post.slug %}" class="cta">Ver más</a>
        </div>
        {% empty %}
        <h3>Sin resultados</h3>
        {% endfor %}
    </div>


    {% if is_paginated %}
    </div>
    <h2 class="listpagetitle">Página</h2>
    <ul class="pagination">

        {% if page_obj.has_previous %}
        <li><a href="?page={{page_obj.previous_page_number}}">«</a></li>
        {% endif %}

        {% for pagina in paginator.page_range %}

        {% ifequal pagina page_obj.number  %}
        <li><a class="active" href="#">{{pagina}}</a></li>
        {% else %}
        <li><a href="?page={{pagina}}">{{pagina}}</a></li>
        {% endifequal %}

        {% endfor %}

        {% if page_obj.has_next %}
        <li><a href="?page={{page_obj.next_page_number}}">»</a></li>
        {% endif %}
    </ul>
    </div>
    {% endif %}
</section>
{% include 'includes/footer.html' %}
{% endblock content %}

Salvemos/templates/Posts/new_post.html
{% extends "Posts/base_posts.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/style-new_post.css' %}">
{% endblock css %}

{% block title %}
Nuevo Post
{% endblock title %}

{% block content %}
{% include 'includes/header_posts.html' %}
<section class="newpost">
    <figure class="newpost__picture">
        <img src="{% static 'img/imgpost.svg' %}" alt="Imagen del new post" class="newpost__img">
    </figure>

    <figure class="newpost__picture2">
        <img src="{% static 'img/imgpost2.svg' %}" alt="Imagen del new post" class="newpost__img">
    </figure>

    <form class="newpost__form" method="post" enctype="multipart/form-data">{% csrf_token %}
        <h2 class="newpost__title title">Nuevo post</h2>
        <h4>Nombre de la mascota</h4>{{form.title}}
        <h4>Qué piensas hacer con tu peludo</h4>{{form.category}}
        <h4>Danos un breve resumen</h4>{{form.resume}}
        <h4>Sube una imagen de la mascota</h4>{{form.image}}
        <h4>Ahora cuentanos todo acerca de la mascota</h4>{{form.content}}
        {{form.media}}
        <div class="newpost__btn">
            <button type="submit" class="newpost__cta">Publicar</button>
        </div>
    </form>
</section>
{% endblock content %}

Salvemos/templates/Posts/post_detail.html
{% extends "Posts/base_posts.html" %}

{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/style-post_detail.css' %}">
<script src="https://kit.fontawesome.com/b814c54e34.js" crossorigin="anonymous"></script>
{% endblock css %}

{% block title %}
Nuevo Post
{% endblock title %}

{% block content %}
{% include 'includes/header_posts.html' %}
<section class="detail__main container">
    <div class="detail__texts">
        <h1 class="detail__title">{{object.title}}</h1>
        <h2 class="detail__paragraph">{{object.resume}}</h2>
        <p>{{object.content | safe}}</p>

    </div>
    <div class="detail__aside">
        <figure class="detail__picture">
            <img src="{{object.image.url}}" alt="" class="detail__img">
        </figure>
        <form action="{% url 'Users_app:addfavorito' posts.id %}" method="post">{% csrf_token %}
            <button type="submit" class="cta">Agregar a favoritos</button>
        </form>

    </div>

</section>
{% include 'includes/footer.html' %}
{% endblock content %}